### ISSUE TITLE
[Improvement] Use hash to invalidade cache

### ISSUE THREAD

**Issue by felipebaltazar** [felipebaltazar/Xamarin.Forms.EmbeddedAssets#1]
## Overview
We need to provide a way to invalidate cache when asset is updated.
The suggestion here is to use Hash (md5) as asset name

## Tasks

- [ ] Change the loader to check embedded resource md5
- [ ] Make a function to clean "expired" cache files
- [ ] Change de file name to use Hash (MD5)
